language: cpp

dist: xenial
addons:
    apt:
        sources:
            - sourceline: 'ppa:mhier/libboost-latest'
        packages:
            - boost1.67
            - libjudy-dev

compiler:
    - g++

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELEASE

script:
    - VERBOSE=ON make

after_success:
    - make test
